const CurrencyActionTypes = {
  FETCH_CURRENCY_SYMBOLS_SUCCES: " FETCH_CURRENCY_SYMBOLS_SUCCES",
  FETCH_CURRENCY_RATES: "FETCH_CURRENCY_RATES",
  ADD_CURRENCIES: "ADD_CURRENCIES",
  REMOVE_CURRENCY: "REMOVE_CURRENCY",
  GET_BASE_CURRENCY: "GET_BASE_CURRENCY",
};

export default CurrencyActionTypes;
